name: test-adapter
on: [pull_request, issue_comment]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: 'json'
          fileOutput: 'json'
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run changes files through test script
        run: |
          RUN_FILES=$(
            MODIFIED=${{ steps.file_changes.outputs.files_modified}} \
            ADDED=${{ steps.file_changes.outputs.files_added}} \
            node ${{ github.workspace }}/.github/workflows/getFileList.js
          )

          if [ "$RUN_FILES" = "[]" ]; then
            echo "No adapter files were modified"
            exit 0
          fi

          yarn install --production
          yarn upgrade @defillama/sdk

          list=$(echo $RUN_FILES | tr  -d '"[]' | tr "," "\n")
          list_changes=("${list[:1]}")
          type=${list[0]}

          for i in ${list_changes}
          do 
            { 
              IFS='@' read -r -a array <<< "$i"
              yarn test ${array[0]} ${array[0]} 2>&1 | tee output.txt
              node ${{ github.workspace }}/.github/workflows/commentResult.js /home/runner/work/adapters/adapters/output.txt "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.number }}" ${i}
              if grep -q "\-\-\-\- ERROR \-\-\-\-" output.txt; then
                exit 1;
              fi
            } || { 
              echo -n $i
              echo ' doesnt run'
            }
          done