name: Check ts

on: [pull_request]
    
jobs:
  ts-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn run update-submodules
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: yarn
    - name: Checking adapters
      run: yarn run ts-check
    - name: Checking cli
      run: yarn run ts-check-cli